# Generated by Django 5.1.7 on 2025-04-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='special_note',
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='TEMP', max_length=20),
        ),
    ]
