# Generated by Django 5.1.7 on 2025-04-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentacademicrecord_studentclasshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.URLField(blank=True, default='https://cdn-icons-png.flaticon.com/512/8847/8847419.png', null=True),
        ),
    ]
