# Generated by Django 5.1.7 on 2025-04-24 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
        ('students', '0005_alter_student_profile_image'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('date', models.DateField()),
                ('attendance_type', models.CharField(choices=[('absence', '결석'), ('lateness', '지각'), ('earlyLeave', '조퇴'), ('result', '결과')], max_length=20)),
                ('reason_type', models.CharField(choices=[('illness', '질병'), ('unauthorized', '미인정'), ('etc', '기타')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'grade', 'year', 'attendance_type', 'reason_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('total_days', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('home_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'grade', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
