# Generated by Django 5.1.7 on 2025-04-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_attendancerecord_attendancesummary_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesummary',
            name='home_teacher',
            field=models.CharField(default='박선생', max_length=50),
            preserve_default=False,
        ),
    ]
