# Generated by Django 5.1.7 on 2025-05-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('grade_status', models.CharField(choices=[('입력완료', '입력완료'), ('임시저장', '임시저장'), ('미입력', '미입력')], max_length=20)),
                ('updated_at', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveSmallIntegerField()),
                ('midterm', models.FloatField()),
                ('final', models.FloatField()),
                ('performance', models.FloatField()),
                ('total_score', models.FloatField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('grade_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.gradegroup')),
            ],
        ),
    ]
