# Generated by Django 5.1.7 on 2025-04-24 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_remove_grade_subject_grade_subject'),
        ('students', '0005_alter_student_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='score',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.AddField(
            model_name='grade',
            name='credits',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='final',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='midterm',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='performance',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='total_score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GradeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('grade_status', models.CharField(choices=[('입력완료', '입력완료'), ('임시저장', '임시저장'), ('미입력', '미입력')], max_length=20)),
                ('updated_at', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.gradegroup'),
        ),
    ]
