# Generated by Django 5.1.7 on 2025-05-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_approval_status_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_type',
            field=models.CharField(blank=True, choices=[('kakao', 'Kakao'), ('google', 'Google'), ('naver', 'Naver')], max_length=10, null=True),
        ),
    ]
