# Generated by Django 5.1.7 on 2025-04-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
