# Generated by Django 5.1.7 on 2025-04-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacher_department_teacher_teacher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
