# Generated by Django 5.1.7 on 2025-04-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentstudent',
            name='role',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother')], default='father', max_length=10),
            preserve_default=False,
        ),
    ]
